* clean up, rename fstats
* clean up confidence region stuff?
  Options:
  1) Delete it entirely
  2) DemoModel has method for testing/CI
  3) DemoModel returns a GodambeConfRegion object which contains all the user-facing methods
  
     Leaning towards option (3).
     
     Don't have any of the delta method scaling business though. Just create a scaled/unscaled Godambe object by passing in a scaled/unscaled demo function directly
  
* get all unit tests working
* get rid of old demography format in unit tests
* allow to set submodel in set_random_parameters
* clean up tutorial
* documentation
* do some of the data parsing in C?
* Fix demo_plotter RuntimeWarning
  /nfs/team118/jk21/miniconda3/lib/python3.6/site-packages/momi/demo_plotter
.py:35: RuntimeWarning: invalid value encountered in double_scalars
  -self.curr_g * (nxt_t - self.curr_t))
  
* sometimes have sfs/denom be 0/0 in multinomial likelihood
  only in extreme cases when N is tiny or huge. should we try to fix this?

* rename Demography to MultipopMoran
* method to compute tensor product, other stats
* use per-base mutation rate?
  require user to supply total number of bases
* improve drawing api
* allow Sfs object to be passed to set_data()
  partially implemented for some unit tests, but will crash if Sfs has wrong set of populations, etc.

* add test for inferring mutation rate
  both with hets, and with total branch len
  (also check if I am scaling mutation rate correctly internally!)
* nuke SfsLikelihoodSurface
  or at least don't make it accessible to the user
