* documentation
* polish tutorial
** add pairwise distances cell
* link Demography graph to DemoPlotter more directly
  so that DemoPlotter can easily show if there is a bug or not
* clean up confidence region stuff
  Options:
  1) Delete it entirely
  2) DemoModel has method for testing/CI
  3) DemoModel returns a GodambeConfRegion object which contains all the user-facing methods
  
     Leaning towards option (3).
     
     Don't have any of the delta method scaling business though. Just create a scaled/unscaled Godambe object by passing in a scaled/unscaled demo function directly
  
     Currently leaning towards cleaning it up and documenting it, but not illustrating it in the tutorial.

* get all unit tests working
* make sure there are unit tests for inferring with missing data
* Fix demo_plotter RuntimeWarning
  /nfs/team118/jk21/miniconda3/lib/python3.6/site-packages/momi/demo_plotter
.py:35: RuntimeWarning: invalid value encountered in double_scalars
  -self.curr_g * (nxt_t - self.curr_t))
  
* sometimes have sfs/denom be 0/0 in multinomial likelihood
  only in extreme cases when N is tiny or huge. should we try to fix this?

* rename Demography to MultipopMoran
