package:
  name: momi
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default').lstrip('v') }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

source:
  git_url: ../

requirements:
  build:
    - gcc_linux-64 # [linux]
    - clang_osx-64 # [osx]
    - openmp # [osx]
    - python {{ python }}
    - setuptools
    - numpy
  run:
    - python
    - libgcc # [linux]
    - openmp # [osx]
    - openblas
    - numpy
    - scipy
    - autograd
    - cached-property
    - networkx
    - pandas
    - msprime >=0.5.0
    - matplotlib
    - seaborn
    - pysam

test:
  requires:
    - pytest
  imports:
    - momi
  source_files:
    - test/demo_utils.py
    - test/test_sfs.py
    - test/test_sfs.pickle
  commands:
    - pytest test/test_sfs.py

about:
  home: https://github.com/jackkamm/momi2
  license: GPLv3
  license_file: LICENSE
